version: '3'

services:
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: tzj-daryl
            MYSQL_PASSWORD: password
        networks:
            - airflow-docker_default
        restart: always
        volumes:
            - ./db:/var/lib/mysql

networks:
    airflow-docker_default:
        external: true
